### ISSUE TITLE
카메라 관련

### ISSUE THREAD

**Issue by gogumaC** [Box-size/box.size-android#1]
## TODO
- [x] 디버깅용 이미지 프래그먼트 만들기 (7/24)
- [x] 카메라 디지털줌 등 사용자 조정 막기
- [x] exif뜯어서 초점거리 뽑기

---
## 공부할것
- [x] 이미지 센서 크기
